k8s: Unify k8s generation logic
This commit is to move deepequal-gen step to the existing k8s-code-gen
for easier maintenance. One point worth noting is the new parser used
in deepequal-gen now requires no compilation error for input package, so
this step should be done after client generation to avoid the below
issue.

```
Error: pkg/k8s/slim/k8s/apiextensions-clientset/clientset.go:18:2: cannot find module providing package github.com/cilium/cilium/pkg/k8s/slim/k8s/apiextensions-client/clientset/versioned/typed/apiextensions/v1: import lookup disabled by -mod=vendor
	(Go version in go.mod is at least 1.14 and vendor directory exists.)
error(s) in "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/fake":
...
```

Signed-off-by: Tam Mach <tam.mach@cilium.io>